theme: jekyll-theme-minimal
title: Arno Laurie
description: Robotics Engineer — EPFL | Autonomous Navigation, Sensor Fusion, ROS2

defaults:
  - scope:
      path: ""
    values:
      layout: default
