theme: jekyll-theme-minimal
title: Arno Laurie
description: State Estimation & Navigation — Robotics MSc EPFL | Factor Graphs, SLAM, EKF/UKF, GNSS/PNT, ROS2 | ERC 2025 & 2026 Winner

defaults:
  - scope:
      path: ""
    values:
      layout: default
